console.log('1. Fibonacci sequence');
require('./src/1-FibonacciSequence/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('2. Factorial of a number');
console.log('');
require('./src/2-FactorialOfNumber/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('3. Prime Number');
console.log('');
require('./src/3-PrimeNumber/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('3a. Optimal Solution for Prime Number');
console.log('');
require('./src/3-PrimeNumber/optimalSolutionWithoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('4. Power of two');
console.log('');
require('./src/4-PowerOfTwo');
console.log('');
console.log('');
console.log('');
console.log('4a. Power of two using bitwise');
console.log('');
require('./src/4-PowerOfTwo/powerOfTwoUsingBitwise.js');
console.log('');
console.log('');
console.log('');
console.log('1a. Fibonacci sequence with recursion');
console.log('');
require('./src/1-FibonacciSequence/withRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('2a. Factorial of a number with recursion');
console.log('');
require('./src/2-FactorialOfNumber/withRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('5. Linear serach');
console.log('');
require('./src/5-LinearSearch');
console.log('');
console.log('');
console.log('');
console.log('6. Binary search');
console.log('');
require('./src/6-BinarySearch');
console.log('');
console.log('');
console.log('');
console.log('6a. Binary search with recursion');
console.log('');
require('./src/6-BinarySearch/withRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('7. Bubble sort');
console.log('');
require('./src/7-BubbleSort');
console.log('');
console.log('');
console.log('');
console.log('8. Insertion sort');
console.log('');
require('./src/8-InsertionSort');
console.log('');
console.log('');
console.log('');
console.log('9. Quick sort');
console.log('');
require('./src/9-QuickSort');
