console.log('1. Fibonacci sequence');
require('./src/1-FibonacciSequence/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('2. Factorial of a number');
console.log('');
require('./src/2-FactorialOfNumber/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('3. Prime Number');
console.log('');
require('./src/3-PrimeNumber/withoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('3(a). Optimal Solution for Prime Number');
console.log('');
require('./src/3-PrimeNumber/optimalSolutionWithoutRecursion.js');
console.log('');
console.log('');
console.log('');
console.log('4. Power of two');
console.log('');
require('./src/4-PowerOfTwo');
console.log('');
console.log('');
console.log('');
console.log('4(a). Power of two using bitwise');
console.log('');
require('./src/4-PowerOfTwo/powerOfTwoUsingBitwise.js');
console.log('');
console.log('');
console.log('');
console.log('5. Fibonacci sequence with recursion');
console.log('');
require('./src/1-FibonacciSequence/withRecursion.js');
